

POST http://localhost:8080/api/user/create
Content-Type: application/json


{
  "login": "zofcia",
  "passwd": "slo"
}

####

GET localhost:8080/backend/rest/user/janek123

####


POST http://localhost:8080/api/mieszkania/create
Content-Type: application/json

{
  "kodPocztowy": "00-001",
  "miasto": "Krakow",
  "ulica": "Al. 29 Listopada",
  "numer": "10",
  "numerMieszkania": "15",
  "nrDzialki": "123/45",
  "nrKsiegiWieczystej": "KR1M/00012345/6",
  "rozmiar": 55.5,
  "pokoje": 3,
  "pietro": 2,
  "piwnica": true,
  "cena": 570000.0,
  "wadium": 10000.0,
  "terminOgledzin": "2025-09-15T14:00:00"
}

###
GET http://localhost:8080/api/mieszkania

###
POST http://localhost:8080/api/mieszkania/filter
Content-Type: application/json

{
  "minCena": 500000.00,
  "maxCena": 600000.00
}

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "zofcia",
  "passwd": "slo"
}

###

GET http://localhost:8080/api/user/adam1